### ISSUE TITLE
Milestone code cleanup.

### ISSUE THREAD

**Issue by dmitriy-shmilo** [dmitriy-shmilo/spreadsheet#30]
- [x] Document all public members.
- [x] Place mark separators in bigger classes.
- [x] Make sure each class and struct is in a separate file.
- [x] Make member naming consistent.
